spring:
  application:
    name: 'apiWallet'

  sql:
    init:
      mode: ALWAYS
  datasource:
    driver-class-name: org.h2.Driver
    #DATABASE_TO_LOWER -> not allow column name with upper case
    url: jdbc:h2:mem:walletdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL;DATABASE_TO_LOWER=true
    username: root
    password: 'root'
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none #create tables if not exists when set update
    #database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

caching:
  spring:
    typeWalletMovementsTTL: 120000